Repository neicnordic/sda-mq, pull requests merged in 2022-01, with the labels that each got.

#23 address wrong path for config files
  Dockerfile
Labels: bug

#27 Update README #none
  README.md
Labels: documentation

#26 Integration test
  .github/integration/cega.conf
  .github/integration/cega.json
  .github/integration/cega.plugins
  .github/integration/config.yaml
  .github/integration/docker-compose.yml
  .github/integration/setup/10_make_certs.sh
  .github/integration/setup/11_create_c4gh_key.sh
  .github/integration/setup/15_services.sh
  .github/integration/setup/20_posix_permissions.sh
  .github/integration/setup/25_create_and_encrypt_file.sh
  .github/integration/setup/ssl.cnf
  .github/integration/tests/30_ingest_test.sh
  .github/workflows/integration.yaml
  .gitignore
  entrypoint.sh
Labels: enhancement
